// Auto-match team name to official vector SVG logos from /public/logos/
const OFFICIAL_LOGOS_MAP: Record<string, string> = {
  'navi': '/logos/natus vincere.svg',
  'na-vi': '/logos/natus vincere.svg',
  'natusvincere': '/logos/natus vincere.svg',
  'faze': '/logos/faze.webp',
  'fazeclan': '/logos/faze.webp',
  'spirit': '/logos/team spirit.webp',
  'teamspirit': '/logos/team spirit.webp',
  'g2': '/logos/g2.webp',
  'g2esports': '/logos/g2.webp',
  'vitality': '/logos/vitality.webp',
  'teamvitality': '/logos/vitality.webp',
  'mouz': '/logos/mouz.svg',
  'mousesports': '/logos/mouz.svg',
  'virtuspro': '/logos/virtus pro.svg',
  'virtus.pro': '/logos/virtus pro.svg',
  'vp': '/logos/virtus pro.svg',
  'astralis': '/logos/astralis.svg',
  'cloud9': '/logos/cloud9.svg',
  'c9': '/logos/cloud9.svg',
  'liquid': '/logos/liquid.svg',
  'teamliquid': '/logos/liquid.svg',
  'heroic': '/logos/heroic.webp',
  'complexity': '/logos/complexity.svg',
  'col': '/logos/complexity.svg',
  'furia': '/logos/furia.svg',
  'ence': '/logos/ence.svg',
  'mongolz': '/logos/the mongolz.webp',
  'themongolz': '/logos/the mongolz.webp',
  'betboom': '/logos/betboom.webp',
  'betboomteam': '/logos/betboom.webp',
  'falcons': '/logos/team falcons.webp',
  'teamfalcons': '/logos/team falcons.webp',
  'big': '/logos/big.svg',
  'fnatic': '/logos/fnatic.svg',
  'mibr': '/logos/mibr.webp',
  'b8': '/logos/b8.webp',
  'pain': '/logos/pain.webp',
  'aurora': '/logos/aurora.webp',
  '3dmax': '/logos/3dmax.webp',
  'amkal': '/logos/amkal.webp',
  'amkalesports': '/logos/amkal.webp',
  'amkalteam': '/logos/amkal.webp',
  'parivision': '/logos/parivision.webp',
  'monte': '/logos/monte.webp',
  'tyloo': '/logos/tyloo.svg',
  '1win': '/logos/1win.webp',
  'ninjasinpyjamas': '/logos/ninjas in pyjamas.webp',
  'nip': '/logos/nip.webp',
  'saints': '/logos/saints.svg',
  'horizon': '/logos/horizon.png',
  'hzn': '/logos/hzn.png',
  'revival': '/logos/rgg.svg',
  'necessary': '/logos/necessary.svg',
  'bulls': '/logos/madbulls.svg',
  'vpso2': '/logos/virtus pro.svg',
  'streeteight': '/logos/streeteight.svg',
  'str8': '/logos/str8.svg'
};

export function getAutoMatchedVectorLogo(name: string): string | null {
  if (!name || typeof name !== 'string') return null;
  const clean = name.trim().toLowerCase().replace(/[\s\-_.]/g, '');
  return OFFICIAL_LOGOS_MAP[clean] || null;
}
