// Auto-match team name to official vector SVG logos from /public/logos/
const OFFICIAL_LOGOS_MAP: Record<string, string> = {
  'navi': '/logos/navi.svg',
  'na-vi': '/logos/navi.svg',
  'natusvincere': '/logos/navi.svg',
  'faze': '/logos/faze.svg',
  'fazeclan': '/logos/faze.svg',
  'spirit': '/logos/spirit.svg',
  'teamspirit': '/logos/spirit.svg',
  'g2': '/logos/g2.svg',
  'g2esports': '/logos/g2.svg',
  'vitality': '/logos/vitality.svg',
  'teamvitality': '/logos/vitality.svg',
  'mouz': '/logos/mouz.svg',
  'mousesports': '/logos/mouz.svg',
  'virtuspro': '/logos/virtus.pro.svg',
  'virtus.pro': '/logos/virtus.pro.svg',
  'vp': '/logos/virtus.pro.svg',
  'astralis': '/logos/astralis.svg',
  'cloud9': '/logos/cloud9.svg',
  'c9': '/logos/cloud9.svg',
  'liquid': '/logos/liquid.svg',
  'teamliquid': '/logos/liquid.svg',
  'heroic': '/logos/heroic.svg',
  'complexity': '/logos/complexity.svg',
  'col': '/logos/complexity.svg',
  'furia': '/logos/furia.svg',
  'ence': '/logos/ence.svg',
  'mongolz': '/logos/mongolz.svg',
  'themongolz': '/logos/mongolz.svg',
  'eternalfire': '/logos/eternal-fire.svg',
  'betboom': '/logos/betboom.svg',
  'betboomteam': '/logos/betboom.svg',
  'falcons': '/logos/falcons.svg',
  'teamfalcons': '/logos/falcons.svg',
  'nemiga': '/logos/nemiga.svg',
  'big': '/logos/big.svg',
  'fnatic': '/logos/fnatic.svg',
  'mibr': '/logos/mibr.svg',
  'flyquest': '/logos/flyquest.svg',
  '9ine': '/logos/9ine.svg',
  'b8': '/logos/b8.svg',
  'pain': '/logos/pain.svg',
  'imperial': '/logos/imperial.svg',
  'saw': '/logos/saw.svg',
  'aurora': '/logos/aurora.svg',
  '3dmax': '/logos/3dmax.svg',
  'amkal': '/logos/amka.svg',
  'parivision': '/logos/pari-vision.svg',
  'pari-vision': '/logos/pari-vision.svg',
  'monte': '/logos/monte.svg',
  'apeks': '/logos/apeks.svg',
  'gamerlegion': '/logos/gamer-legion.svg',
  'tyloo': '/logos/tyloo.svg',
  'lynnvision': '/logos/lynn-vision.svg',
  '1win': '/logos/1win.svg',
  'sinners': '/logos/sinners.svg',
  'og': '/logos/og.svg',
  'outsiders': '/logos/outsiders.svg',
  'dignitas': '/logos/dignitas.svg',
  'ninjasinpyjamas': '/logos/nip.svg',
  'nip': '/logos/nip.svg'
};

export function getAutoMatchedVectorLogo(name: string): string | null {
  if (!name || typeof name !== 'string') return null;
  const clean = name.trim().toLowerCase().replace(/[\s\-_.]/g, '');
  return OFFICIAL_LOGOS_MAP[clean] || null;
}
