const fs = require('fs');
let code = fs.readFileSync('src/match-logic/engine/RoundEngine.ts', 'utf-8');

code = code.replace(
    '    } else if (state.round > regulationMax) {\n      const otRound = state.round - regulationMax;\n      if (otRound === 1 || (otRound - 1) % 6 === 0) {\n        if (teamIds[0] && state.teams[teamIds[0]]) state.teams[teamIds[0]].side = t1Orig;\n        if (teamIds[1] && state.teams[teamIds[1]]) state.teams[teamIds[1]].side = t2Orig;\n        for (const p of Object.values(state.players)) {\n          if (p) {\n            p.side = state.teams[p.teamId]?.side || \'T\';\n            p.money = 10000;\n          }\n        }\n      } else if ((otRound - 1) % 3 === 0) {\n        if (teamIds[0] && state.teams[teamIds[0]]) state.teams[teamIds[0]].side = t1Orig === \'T\' ? \'CT\' : \'T\';\n        if (teamIds[1] && state.teams[teamIds[1]]) state.teams[teamIds[1]].side = t2Orig === \'T\' ? \'CT\' : \'T\';\n        for (const p of Object.values(state.players)) {\n          if (p) {\n            p.side = state.teams[p.teamId]?.side || \'T\';\n            p.money = 10000;\n          }\n        }\n      }\n    }',
    '    } else if (state.round > regulationMax) {\n      const otRound = state.round - regulationMax;\n      const roundsPerHalf = state.isCS2 ? 3 : 2;\n      const roundsPerOT = roundsPerHalf * 2;\n      if (otRound === 1 || (otRound - 1) % roundsPerOT === 0) {\n        if (teamIds[0] && state.teams[teamIds[0]]) state.teams[teamIds[0]].side = t1Orig;\n        if (teamIds[1] && state.teams[teamIds[1]]) state.teams[teamIds[1]].side = t2Orig;\n        for (const p of Object.values(state.players)) {\n          if (p) {\n            p.side = state.teams[p.teamId]?.side || \'T\';\n            p.money = 10000;\n          }\n        }\n      } else if ((otRound - 1) % roundsPerHalf === 0) {\n        if (teamIds[0] && state.teams[teamIds[0]]) state.teams[teamIds[0]].side = t1Orig === \'T\' ? \'CT\' : \'T\';\n        if (teamIds[1] && state.teams[teamIds[1]]) state.teams[teamIds[1]].side = t2Orig === \'T\' ? \'CT\' : \'T\';\n        for (const p of Object.values(state.players)) {\n          if (p) {\n            p.side = state.teams[p.teamId]?.side || \'T\';\n            p.money = 10000;\n          }\n        }\n      }\n    }'
);

fs.writeFileSync('src/match-logic/engine/RoundEngine.ts', code);
console.log('RoundEngine patched.');
